apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tap-full-profile-cluster
  namespace: test-namespace
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: guaranteed-medium
      storageClass: tanzu-gold-storage-policy
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
    nodePools:
      - name: workers
        storageClass: tanzu-gold-storage-policy
        vmClass: guaranteed-large
        replicas: 5
        volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 120Gi
        tkr:
          reference:
            name: v1.23.8---vmware.3-tkg.1
  settings:
    storage:
      defaultClass: tanzu-gold-storage-policy
