apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: rabbitmq-preprovisioned-small
spec:
  description:
    short: RabbitMQ Cluster with 1 Replica
  pool:
    group: rabbitmq.com
    kind: RabbitmqCluster
    labelSelector:
      matchLabels:
        services.apps.tanzu.vmware.com/class: rmq-small
