---
apiVersion: v1
kind: Secret
metadata:
  name: secret1
stringData:
  userId: user1
  password: password-1
---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
stringData:
  userId: user2
  password: password-2
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    tty: true
    stdin: true
    volumeMounts:
    - name: binding1
      mountPath: "/bindings/secret1"
      readOnly: true
    - name: binding2
      mountPath: "/bindings/secret2"
      readOnly: true
  volumes:
  - name: binding1
    projected:
      sources:
      - secret:
          name: secret1
  - name: binding2
    projected:
      sources:
      - secret:
          name: secret2
