#@ load("@ytt:data", "data")
---
apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: fhir-postgres
  namespace: #@ data.values.namespace
spec:
  name: postgres
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ClassClaim
    name: hapi-postgres
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: hapi-fhir
